export const weatherConstants = {
  LOCATIONS_FETCH_STARTED: 'LOCATIONS_FETCH_STARTED',
  LOCATIONS_FETCH_SUCCESS: 'LOCATIONS_FETCH_SUCCESS',
  LOCATIONS_FETCH_FAILURE: 'LOCATIONS_FETCH_FAILURE',
  SET_CURRENT_LOCATION: 'SET_CURRENT_LOCATION',
  CURRENT_LOCATION_WEATHER_FETCH_STARTED:
    'CURRENT_LOCATION_WEATHER_FETCH_STARTED',
  CURRENT_LOCATION_WEATHER_FETCH_SUCCESS:
    'CURRENT_LOCATION_WEATHER_FETCH_SUCCESS',
  CURRENT_LOCATION_WEATHER_FETCH_FAILURE:
    'CURRENT_LOCATION_WEATHER_FETCH_FAILURE',
  CURRENT_LOCATION_HISTORICAL_WEATHER_FETCH_STARTED:
    'CURRENT_LOCATION_HISTORICAL_WEATHER_FETCH_STARTED',
  CURRENT_LOCATION_HISTORICAL_WEATHER_FETCH_SUCCESS:
    'CURRENT_LOCATION_HISTORICAL_WEATHER_FETCH_SUCCESS',
  CURRENT_LOCATION_HISTORICAL_WEATHER_FETCH_FAILURE:
    'CURRENT_LOCATION_HISTORICAL_WEATHER_FETCH_FAILURE',
  CLEAR_LOCATIONS: 'CLEAR_LOCATIONS',
  SET_HOME_LOCATION: 'SET_HOME_LOCATION',
  HOME_LOCATION_WEATHER_FETCH_SUCCESS: 'HOME_LOCATION_WEATHER_FETCH_SUCCESS',
  HOME_LOCATION_WEATHER_FETCH_FAILURE: 'HOME_LOCATION_WEATHER_FETCH_FAILURE',
  SET_LOADING: 'SET_LOADING',
};
